spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_db_dev
    username: root
    password: Mobile!23
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: jt_database_create.sql
